
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Topbar from "../component/shared/Topbar";
import BottomBar from "../component/shared/BottomBar";
import LeftSIdeBar from "../component/shared/LeftSIdeBar";
import CenterComponent from "../component/shared/CenterComponent";
import RightSIdeBar from "../component/shared/RightSIdeBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <Topbar />
          <main>
            <LeftSIdeBar />
            <section>
              {children}
            </section>
            <RightSIdeBar />
          </main>
          <BottomBar />
        </body>
      </html>
    </ClerkProvider>
  );
}
