import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import TopBar from '@/components/TopBar'
import LeftSideBar from '@/components/LeftSideBar'
import RightSideBar from '@/components/RightSideBar'
import BottomBar from '@/components/BottomSideBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={inter.className}>
        <TopBar/>
        <main>
          {/* <LeftSideBar/> */}
          <section className='main-container'>
            <div className=''>
              {children}
            </div>

          </section>
          {/* <RightSideBar/> */}
        </main>
        {children}
        {/* <BottomBar/> */}
        </body>
    </html>
    </ClerkProvider>
  )
}
